version: '3.8'

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379

  livekit:
    image: livekit/livekit-server
    command: --dev --redis-host redis:6379
    depends_on:
      - redis
    environment:
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
    ports:
      - "7880:7880"  # WebSocket
      - "7881:7881"  # HTTP
    networks:
      - livekit_network

  sip:
    image: livekit/sip
    depends_on:
      - redis
      - livekit
    environment:
      SIP_CONFIG_BODY: |
        api_key: ${LIVEKIT_API_KEY}
        api_secret: ${LIVEKIT_API_SECRET}
        ws_url: 'ws://livekit:7880'
        redis:
          address: 'redis:6379'
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
        trunks:
          - name: "Meu Tronco SIP"
            numbers: ["${SIP_TRUNK_NUMBER}"]  # Número do WhatsApp
            auth_username: "${SIP_TRUNK_USERNAME}"
            auth_password: "${SIP_TRUNK_PASSWORD}"
            address: "${SIP_TRUNK_HOST}"  # Host do seu provedor
    ports:
      - "5060:5060"  # SIP
      - "10000-10002:10000-10002"  # RTP
    networks:
      - livekit_network

  livekit-agent:
    build: .
    container_name: livekit-agent
    depends_on:
      - redis
      - livekit
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - livekit_network

volumes:
  redis_data:

networks:
  livekit_network:
    driver: bridge
